const int sPWMpin1 = 11;
const int sPWMpin2 = 9;
const int sPWMpin3 = 10;
const int sPWMpin4 = 3;

void setup() {
  pinMode(sPWMpin1, OUTPUT);// High 1 
  pinMode(sPWMpin2, OUTPUT);// High 2 
  pinMode(sPWMpin3, OUTPUT); // Low 1
  pinMode(sPWMpin4, OUTPUT); // Low 2  
}

void loop() {

digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin2, LOW);
digitalWrite(sPWMpin4,HIGH);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(0);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(80);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(2);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(76);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(6);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(74);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(8);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(70);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(12);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(68);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(14);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(64);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(17);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(62);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(20);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(59);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(23);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(56);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(26);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(53);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(29);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(50);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(32);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(47);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(34);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(44);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(37);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(42);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(40);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(39);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(42);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(37);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(45);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(34);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(47);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(32);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(50);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(29);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);

delayMicroseconds(52);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(27);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(54);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(25);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(56);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(23);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(58);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(20);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(60);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(18);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(62);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(17);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(64);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(15);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(66);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(13);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(68);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(12);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(69);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(10);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(70);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(8);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(72);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(7);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(73);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(6);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(74);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(5);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(75);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(4);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(76);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(3);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(77);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(2);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(80);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(80);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(77);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(2);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(76);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(2);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(76);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(3);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(75);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(4);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(74);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(5);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(72);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(6);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(71);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(8);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(70);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(9);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(68);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(11);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(67);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(12);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(65);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(14);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(63);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(16);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(61);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(18);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(59);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(20);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(57);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(22);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(55);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(24);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(53);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(26);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(51);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(28);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(48);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(30);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(46);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(33);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(44);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(35);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(41);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(38);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(36);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(43);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(33);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(46);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(30);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(49);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(28);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(52);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(25);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(54);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(22);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(57);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(19);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(60);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(16);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(63);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(13);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(66);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(10);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(69);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(7);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(72);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(4);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(75);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin3,LOW);
digitalWrite(sPWMpin1, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin1,LOW);
digitalWrite(sPWMpin3, HIGH);

delayMicroseconds(80);
  digitalWrite(sPWMpin1,LOW);
  digitalWrite(sPWMpin2,LOW);
  digitalWrite(sPWMpin4,LOW);
  digitalWrite(sPWMpin3,HIGH);


//se repite para semiciclo neg

  digitalWrite(sPWMpin4,LOW);

  digitalWrite(sPWMpin1,LOW);
  
  digitalWrite(sPWMpin3, HIGH);

  digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(0);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(80);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(2);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(76);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(6);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(74);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(8);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(70);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(12);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(68);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(14);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(64);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(17);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(62);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(20);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(59);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(23);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(56);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(26);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(53);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(29);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(50);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(32);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(47);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(34);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(44);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(37);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(42);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(40);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(39);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(42);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(37);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(45);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(34);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(47);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(32);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(50);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(29);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);

delayMicroseconds(52);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(27);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(54);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(25);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(56);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(23);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(58);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(20);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(60);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(18);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(62);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(17);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(64);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(15);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(66);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(13);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(68);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(12);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(69);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(10);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(70);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(8);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(72);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(7);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(73);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(6);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(74);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(5);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(75);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(4);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(76);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(3);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(77);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(2);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(80);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(80);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(79);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(77);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(2);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(76);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(2);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(76);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(3);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(75);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(4);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(74);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(5);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(72);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(6);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(71);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(8);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(70);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(9);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(68);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(11);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(67);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(12);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(65);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(14);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(63);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(16);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(61);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(18);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(59);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(20);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(57);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(22);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(55);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(24);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(53);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(26);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(51);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(28);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(48);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(30);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(46);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(33);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(44);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(35);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(41);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(38);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(36);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(43);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(33);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(46);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(30);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(49);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(28);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(52);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(25);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(54);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(22);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(57);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(19);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(60);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(16);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(63);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(13);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(66);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(10);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(69);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(7);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(72);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(4);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(75);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(1);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);
delayMicroseconds(78);
digitalWrite(sPWMpin4,LOW);
digitalWrite(sPWMpin2, HIGH);
delayMicroseconds(0);
digitalWrite(sPWMpin2,LOW);
digitalWrite(sPWMpin4, HIGH);

delayMicroseconds(80);

  digitalWrite(sPWMpin1,LOW);
 
  digitalWrite(sPWMpin2,LOW);

  digitalWrite(sPWMpin3,LOW);

  digitalWrite(sPWMpin4,HIGH);
 
}